# GitHub Sponsors funding options

github: ["oscharko"]
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: pypi/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name
custom: ["https://keiko.dev/sponsor"]