version: "3.9"
services:
  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: keiko-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./infrastructure/prometheus/rules:/etc/prometheus/rules:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=7d'
    networks:
      - keiko-network
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: keiko-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./infrastructure/alertmanager/config.yml:/etc/alertmanager/alertmanager.yml:ro
    networks:
      - keiko-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.0
    container_name: keiko-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./infrastructure/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

networks:
  keiko-network:
    driver: bridge

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
