# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_stream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "grpc_stream.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11grpc_stream.proto\x12\x15services.streaming.v1"k\n\x0b\x46rameHeader\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tstream_id\x18\x02 \x01(\t\x12\x0b\n\x03seq\x18\x03 \x01(\x03\x12\n\n\x02ts\x18\x04 \x01(\t\x12\x0f\n\x07\x63orr_id\x18\x05 \x01(\t\x12\x13\n\x0btraceparent\x18\x06 \x01(\t"B\n\tChunkInfo\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12\x15\n\rcontent_range\x18\x02 \x01(\t\x12\x10\n\x08\x63hecksum\x18\x03 \x01(\t"S\n\tErrorInfo\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tretryable\x18\x03 \x01(\x08\x12\x14\n\x0c\x64\x65tails_json\x18\x04 \x01(\t":\n\x07\x41\x63kInfo\x12\x0f\n\x07\x61\x63k_seq\x18\x01 \x01(\x03\x12\x0e\n\x06\x63redit\x18\x02 \x01(\x05\x12\x0e\n\x06reason\x18\x03 \x01(\t"\x88\x02\n\x0bStreamFrame\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x32\n\x06header\x18\x02 \x01(\x0b\x32".services.streaming.v1.FrameHeader\x12\x14\n\x0cpayload_json\x18\x03 \x01(\t\x12\x12\n\nbinary_ref\x18\x04 \x01(\t\x12/\n\x05\x63hunk\x18\x05 \x01(\x0b\x32 .services.streaming.v1.ChunkInfo\x12/\n\x05\x65rror\x18\x06 \x01(\x0b\x32 .services.streaming.v1.ErrorInfo\x12+\n\x03\x61\x63k\x18\x07 \x01(\x0b\x32\x1e.services.streaming.v1.AckInfo2j\n\x10KEIStreamService\x12V\n\x06Stream\x12".services.streaming.v1.StreamFrame\x1a".services.streaming.v1.StreamFrame"\x00(\x01\x30\x01\x42\xa0\x01\n\x1f\x63om.keiko.services.streaming.v1P\x01Z]github.com/keiko-platform/services-streaming/gen/go/services/streaming/v1;servicesstreamingv1\xaa\x02\x1bKeiko.Services.Streaming.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "grpc_stream_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals["DESCRIPTOR"]._loaded_options = None
  _globals["DESCRIPTOR"]._serialized_options = b"\n\037com.keiko.services.streaming.v1P\001Z]github.com/keiko-platform/services-streaming/gen/go/services/streaming/v1;servicesstreamingv1\252\002\033Keiko.Services.Streaming.V1"
  _globals["_FRAMEHEADER"]._serialized_start=44
  _globals["_FRAMEHEADER"]._serialized_end=151
  _globals["_CHUNKINFO"]._serialized_start=153
  _globals["_CHUNKINFO"]._serialized_end=219
  _globals["_ERRORINFO"]._serialized_start=221
  _globals["_ERRORINFO"]._serialized_end=304
  _globals["_ACKINFO"]._serialized_start=306
  _globals["_ACKINFO"]._serialized_end=364
  _globals["_STREAMFRAME"]._serialized_start=367
  _globals["_STREAMFRAME"]._serialized_end=631
  _globals["_KEISTREAMSERVICE"]._serialized_start=633
  _globals["_KEISTREAMSERVICE"]._serialized_end=739
# @@protoc_insertion_point(module_scope)
