name: 🔒 Security Vulnerability
description: Report a security vulnerability (private)
title: "[SECURITY] "
labels: ["security", "critical"]
assignees: ["oscharko"]

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: If this is a critical security vulnerability, please report it privately to security@keiko.dev instead of creating a public issue.

  - type: checkboxes
    id: severity-check
    attributes:
      label: Vulnerability Severity
      description: Please assess the severity of this vulnerability
      options:
        - label: 🟢 Low - Minor security improvement
        - label: 🟡 Medium - Potential security risk  
        - label: 🟠 High - Exploitable vulnerability
        - label: 🔴 Critical - Immediate security threat (should be reported privately)

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: Describe the security vulnerability
      placeholder: A detailed description of the security issue, including potential impact.
    validations:
      required: true

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of security vulnerability is this?
      options:
        - Authentication/Authorization
        - Injection (SQL, Command, etc.)
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)  
        - Information Disclosure
        - Cryptographic Issue
        - Dependency Vulnerability
        - Configuration Security
        - Input Validation
        - Other
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: Affected Components
      description: Which parts of the system are affected?
      placeholder: |
        - API endpoints: /api/...
        - Modules: authentication, user management
        - Dependencies: package-name@version
    validations:
      required: true

  - type: textarea
    id: exploitation-steps
    attributes:
      label: Exploitation Steps
      description: How can this vulnerability be exploited? (if safe to describe)
      placeholder: |
        1. Step 1...
        2. Step 2...
        3. Result...
        
        ⚠️ Only include if safe for public disclosure

  - type: textarea
    id: impact-assessment
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this vulnerability?
      placeholder: |
        - Confidentiality: High/Medium/Low
        - Integrity: High/Medium/Low
        - Availability: High/Medium/Low
        - Potential damage: ...
    validations:
      required: true

  - type: textarea
    id: mitigation-suggestions
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for fixing this vulnerability?
      placeholder: Recommendations for addressing the security issue.

  - type: input
    id: version-affected
    attributes:
      label: Affected Version(s)
      description: Which versions are affected by this vulnerability?
      placeholder: "v1.0.0 - v1.2.3, or commit range"
    validations:
      required: true

  - type: checkboxes
    id: disclosure-policy
    attributes:
      label: Responsible Disclosure
      description: Please confirm your understanding of our security policy
      options:
        - label: I understand this issue will be handled according to responsible disclosure practices
          required: true
        - label: I agree to work with the maintainers to resolve this issue before public disclosure
          required: true
        - label: I have not publicly disclosed this vulnerability elsewhere
          required: true