# Production Environment Configuration
# This file defines the protection rules and policies for the production environment

name: production
description: "Production environment with strict protection rules and approval workflows"

# Environment Protection Rules
protection_rules:
  # Required Reviewers
  required_reviewers:
    - type: "users"
      users:
        - "oscharko"  # Primary maintainer
    - type: "teams"
      teams:
        - "keiko-dev-team/maintainers"
        - "keiko-dev-team/senior-developers"
  
  # Minimum number of required approvals
  required_approval_count: 2
  
  # Prevent self-approval
  prevent_self_review: true
  
  # Deployment Branch Policy
  deployment_branch_policy:
    protected_branches: true
    custom_branch_policies:
      - name: "main"
        required: true
      - name: "release/*"
        required: false
        conditions:
          - "starts_with:release/"
          - "matches_pattern:release/v*"

# Deployment Windows
deployment_windows:
  # Business hours deployment window
  business_hours:
    enabled: true
    timezone: "UTC"
    days:
      - "monday"
      - "tuesday" 
      - "wednesday"
      - "thursday"
      - "friday"
    hours:
      start: "09:00"
      end: "17:00"
    
  # Emergency deployment window (24/7)
  emergency:
    enabled: true
    requires_justification: true
    additional_approvals: 1

# Deployment Policies
deployment_policies:
  # Automatic deployment prevention
  prevent_automatic_deployment: true
  
  # Require manual approval for all deployments
  require_manual_approval: true
  
  # Deployment timeout
  deployment_timeout_minutes: 60
  
  # Rollback policies
  rollback:
    enabled: true
    automatic_on_failure: false
    requires_approval: false
    timeout_minutes: 30

# Security Policies
security_policies:
  # Require secrets to be explicitly approved
  require_secret_approval: true
  
  # Audit all deployments
  audit_deployments: true
  
  # Require security scan before deployment
  require_security_scan: true
  
  # Vulnerability threshold
  max_vulnerability_score: 7.0

# Notification Settings
notifications:
  # Notify on deployment start
  on_deployment_start:
    - type: "slack"
      webhook: "${{ secrets.SLACK_DEPLOYMENT_WEBHOOK }}"
    - type: "email"
      recipients:
        - "team@keiko.dev"
  
  # Notify on deployment completion
  on_deployment_complete:
    - type: "slack"
      webhook: "${{ secrets.SLACK_DEPLOYMENT_WEBHOOK }}"
    - type: "email"
      recipients:
        - "team@keiko.dev"
  
  # Notify on deployment failure
  on_deployment_failure:
    - type: "slack"
      webhook: "${{ secrets.SLACK_ALERTS_WEBHOOK }}"
    - type: "email"
      recipients:
        - "alerts@keiko.dev"
    - type: "pagerduty"
      service_key: "${{ secrets.PAGERDUTY_SERVICE_KEY }}"

# Monitoring and Observability
monitoring:
  # Health checks after deployment
  health_checks:
    enabled: true
    endpoints:
      - url: "https://api.keiko.dev/health"
        method: "GET"
        expected_status: 200
        timeout_seconds: 30
      - url: "https://api.keiko.dev/ready"
        method: "GET"
        expected_status: 200
        timeout_seconds: 30
    
    # Health check schedule
    initial_delay_seconds: 60
    check_interval_seconds: 30
    max_checks: 10
    failure_threshold: 3
  
  # Performance monitoring
  performance_monitoring:
    enabled: true
    sla_threshold_seconds: 2.0
    error_rate_threshold: 0.01  # 1%
    monitoring_duration_minutes: 30

# Compliance and Governance
compliance:
  # Change management
  change_management:
    require_change_ticket: true
    ticket_systems:
      - "jira"
      - "github_issues"
  
  # Documentation requirements
  documentation:
    require_deployment_notes: true
    require_rollback_plan: true
    require_testing_evidence: true
  
  # Approval workflow
  approval_workflow:
    stages:
      - name: "technical_review"
        required_approvers: 1
        approver_groups:
          - "keiko-dev-team/senior-developers"
      - name: "security_review"
        required_approvers: 1
        approver_groups:
          - "keiko-dev-team/security-team"
      - name: "business_approval"
        required_approvers: 1
        approver_groups:
          - "keiko-dev-team/product-owners"

# Emergency Procedures
emergency_procedures:
  # Emergency deployment bypass
  emergency_bypass:
    enabled: true
    requires_justification: true
    additional_logging: true
    post_deployment_review: true
  
  # Emergency contacts
  emergency_contacts:
    - name: "Oliver Scharkowski"
      role: "Lead Developer"
      contact: "o.scharkowski@oscharko.de"
      availability: "24/7"
    - name: "DevOps Team"
      role: "Infrastructure"
      contact: "devops@keiko.dev"
      availability: "Business Hours"

# Rollback Configuration
rollback:
  # Automatic rollback triggers
  automatic_triggers:
    - condition: "health_check_failure"
      threshold: 3
      action: "rollback"
    - condition: "error_rate_spike"
      threshold: 0.05  # 5%
      action: "rollback"
    - condition: "response_time_degradation"
      threshold: 5.0  # 5 seconds
      action: "rollback"
  
  # Manual rollback
  manual_rollback:
    enabled: true
    requires_approval: false
    notification_required: true
  
  # Rollback validation
  validation:
    enabled: true
    health_checks: true
    performance_checks: true
    functional_tests: false  # Optional for rollback

# Audit and Logging
audit:
  # Deployment audit trail
  deployment_audit:
    enabled: true
    log_level: "detailed"
    retention_days: 365
  
  # Access audit
  access_audit:
    enabled: true
    log_failed_attempts: true
    log_successful_deployments: true
  
  # Compliance reporting
  compliance_reporting:
    enabled: true
    report_frequency: "monthly"
    report_recipients:
      - "compliance@keiko.dev"
      - "security@keiko.dev"
