# Staging Environment Configuration
# This file defines the protection rules and policies for the staging environment

name: staging
description: "Staging environment for pre-production testing and validation"

# Environment Protection Rules
protection_rules:
  # Required Reviewers (less strict than production)
  required_reviewers:
    - type: "users"
      users:
        - "oscharko"
    - type: "teams"
      teams:
        - "keiko-dev-team/developers"
  
  # Minimum number of required approvals
  required_approval_count: 1
  
  # Allow self-approval for staging
  prevent_self_review: false
  
  # Deployment Branch Policy
  deployment_branch_policy:
    protected_branches: false
    custom_branch_policies:
      - name: "main"
        required: false
      - name: "develop"
        required: false
      - name: "feature/*"
        required: false
        conditions:
          - "starts_with:feature/"
      - name: "release/*"
        required: false
        conditions:
          - "starts_with:release/"

# Deployment Windows (more flexible than production)
deployment_windows:
  # Extended deployment window
  business_hours:
    enabled: false  # Allow deployments anytime
    timezone: "UTC"
    
  # Emergency deployment (always available)
  emergency:
    enabled: true
    requires_justification: false
    additional_approvals: 0

# Deployment Policies
deployment_policies:
  # Allow automatic deployment for staging
  prevent_automatic_deployment: false
  
  # Manual approval optional
  require_manual_approval: false
  
  # Deployment timeout
  deployment_timeout_minutes: 45
  
  # Rollback policies
  rollback:
    enabled: true
    automatic_on_failure: true
    requires_approval: false
    timeout_minutes: 15

# Security Policies (relaxed for staging)
security_policies:
  # Secrets approval not required for staging
  require_secret_approval: false
  
  # Audit deployments
  audit_deployments: true
  
  # Security scan recommended but not required
  require_security_scan: false
  
  # Higher vulnerability threshold for staging
  max_vulnerability_score: 9.0

# Notification Settings
notifications:
  # Notify on deployment start
  on_deployment_start:
    - type: "slack"
      webhook: "${{ secrets.SLACK_STAGING_WEBHOOK }}"
  
  # Notify on deployment failure
  on_deployment_failure:
    - type: "slack"
      webhook: "${{ secrets.SLACK_STAGING_WEBHOOK }}"

# Monitoring and Observability
monitoring:
  # Health checks after deployment
  health_checks:
    enabled: true
    endpoints:
      - url: "https://staging-api.keiko.dev/health"
        method: "GET"
        expected_status: 200
        timeout_seconds: 30
    
    # Health check schedule
    initial_delay_seconds: 30
    check_interval_seconds: 30
    max_checks: 5
    failure_threshold: 2
  
  # Performance monitoring (relaxed)
  performance_monitoring:
    enabled: true
    sla_threshold_seconds: 5.0
    error_rate_threshold: 0.05  # 5%
    monitoring_duration_minutes: 15

# Compliance and Governance (simplified)
compliance:
  # Change management (optional)
  change_management:
    require_change_ticket: false
  
  # Documentation requirements (minimal)
  documentation:
    require_deployment_notes: false
    require_rollback_plan: false
    require_testing_evidence: false
  
  # Simplified approval workflow
  approval_workflow:
    stages:
      - name: "technical_review"
        required_approvers: 1
        approver_groups:
          - "keiko-dev-team/developers"

# Rollback Configuration
rollback:
  # Automatic rollback triggers
  automatic_triggers:
    - condition: "health_check_failure"
      threshold: 2
      action: "rollback"
    - condition: "error_rate_spike"
      threshold: 0.10  # 10%
      action: "rollback"
  
  # Manual rollback
  manual_rollback:
    enabled: true
    requires_approval: false
    notification_required: false

# Audit and Logging (basic)
audit:
  # Deployment audit trail
  deployment_audit:
    enabled: true
    log_level: "basic"
    retention_days: 90
  
  # Access audit
  access_audit:
    enabled: false
