server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: varlogs
    static_configs:
      - targets: [localhost]
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: keiko-backend
    static_configs:
      - targets: [localhost]
        labels:
          job: keiko-backend
          env: ${ENVIRONMENT:-development}
          service: keiko-backend
          __path__: /app/backend-logs/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            correlation_id: correlation_id
            tenant: tenant
      - labels:
          level:
          tenant:
      - output:
          source: message
