groups:
  - name: keiko.sla
    interval: 30s
    rules:
      - alert: ApiResponseTimeWarning
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "API Antwortzeit > 2s"
          description: "P95 Antwortzeit {{ $value }}s"

      - alert: ApiResponseTimeCritical
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 5
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "API Antwortzeit > 5s"
          description: "P95 Antwortzeit {{ $value }}s"

      - alert: ErrorRateWarning
        expr: (rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m])) > 0.01
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Error Rate > 1%"
          description: "{{ $value | humanizePercentage }}"

      - alert: ErrorRateCritical
        expr: (rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m])) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Error Rate > 5%"
          description: "{{ $value | humanizePercentage }}"
