# Führt schnelle, isolierte Import-/Lazy-Loader-Tests ohne Coverage aus
# Zweck: Schnelles Feedback, unabhängig von globalen 85%-Coverage-Gates

name: quick-import-tests

on:
  push:
    branches: [ main ]
    branches-ignore: [dev]  # Keine Import-Tests beim Merge nach dev
  pull_request:
    branches: [ main ]
    branches-ignore: [dev]  # Keine Import-Tests bei PRs nach dev

jobs:
  lazy-loader-tests:
    name: Lazy-Loader Import Tests (ohne Coverage)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies (Test-Extras)
        # Deutsche Kommentare: Installiert Projekt im Editable-Modus + Test-Extras
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[test]

      - name: Run quick import tests (ohne Coverage)
        # Deutsche Kommentare: führt nur die Lazy-Import Tests aus, ohne globale Addopts
        working-directory: backend
        run: |
          pytest tests/unit/services/test_webhook_lazy_import.py -q -p no:cov -o addopts=


  full-suite-tests:
    name: Full Test Suite mit Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies (Test-Extras)
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[test]

      - name: Run full test suite with coverage
        working-directory: backend
        run: |
          pytest

